require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# platform :ios, '10.0' CocoaPods could not find compatible versions for pod "react-native-ffmpeg/https": が出たので 10 => 11にした
platform :ios, '11.0'
use_frameworks!

def shared_pods
  pod 'react-native-video/VideoCaching', :path => '../node_modules/react-native-video/react-native-video.podspec'
  
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'RNToasty', :path => '../node_modules/react-native-toasty/ios'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
    #flipper_post_install(installer)
  #end
end

target 'rn_app' do
  target 'rn_appTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'rn_app-stg' do
  shared_pods
end

target 'rn_app-dev' do
  shared_pods
end

target 'rn_app-tvOS' do
  # Pods for rn_app-tvOS

  target 'rn_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
