require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# platform :ios, '10.0' CocoaPods could not find compatible versions for pod "react-native-ffmpeg/https": が出たので 10 => 11にした
platform :ios, '11.0'
use_frameworks!

target 'rn_app' do
  
  # 依存関係のエラーが出るのでuse_native_modules!の前に置く
  # https://github.com/tanersener/react-native-ffmpeg
  # Note that if you have use_native_modules! in your Podfile, specifying a subspec may cause the following error. You can fix it by defining react-native-ffmpeg dependency before use_native_modules! in your Podfile.
  #pod 'react-native-ffmpeg/min-gpl', :podspec => '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec'
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'RNToasty', :path => '../node_modules/react-native-toasty/ios'
  

  target 'rn_appTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
    #flipper_post_install(installer)
  #end
end

target 'rn_app-tvOS' do
  # Pods for rn_app-tvOS

  target 'rn_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
